blank_issues_enabled: true
contact_links:
  - name: jDriveClonr Question
    url: https://github.com/username/jDriveClonr/discussions
    about: Please ask and answer questions here.
  - name: jDriveClonr Documentation
    url: https://github.com/username/jDriveClonr/blob/main/README.md
    about: Check the documentation for answers to common questions.
